#!/usr/bin/env python3
"""
Create one GIF for the EM-planner demo.

Inputs default to output/<scenario>/csv files generated by run_demo.py:
  - global_path_world_points.csv
  - reference_line_motion.csv
  - obstacles.csv
  - ego_trajectory.csv

The ego_trajectory.csv file is written by the C++ plugin and contains the
per-frame DP path after Frenet-to-Cartesian conversion.
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

def read_global_path(path: Path):
    points = []
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            points.append((float(row["x"]), float(row["y"])))
    return points


def read_reference_motion(path: Path):
    frames = {}
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            frame_id = int(row["frame_id"])
            frames.setdefault(frame_id, []).append(
                {
                    "frame_id": frame_id,
                    "sim_time": float(row["sim_time"]),
                    "ego_x": float(row["ego_x"]),
                    "ego_y": float(row["ego_y"]),
                    "global_match_idx": int(row["global_match_idx"]),
                    "projection_x": float(row["projection_x"]),
                    "projection_y": float(row["projection_y"]),
                    "projection_hdg": float(row["projection_hdg"]),
                    "target_idx": int(row["target_idx"]),
                    "point_idx": int(row["point_idx"]),
                    "ref_s": float(row["ref_s"]),
                    "ref_x": float(row["ref_x"]),
                    "ref_y": float(row["ref_y"]),
                    "target_x": float(row["target_x"]),
                    "target_y": float(row["target_y"]),
                }
            )
    for rows in frames.values():
        rows.sort(key=lambda item: item["point_idx"])
    return frames


def read_ego_trajectory(path: Path):
    frames = {}
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            frame_id = int(row["frame_id"])
            frames.setdefault(frame_id, []).append(
                {
                    "frame_id": frame_id,
                    "sim_time": float(row["sim_time"]),
                    "time_step": float(row["time_step"]),
                    "ego_x": float(row["ego_x"]),
                    "ego_y": float(row["ego_y"]),
                    "ego_h": float(row["ego_h"]),
                    "target_idx": int(row["target_idx"]),
                    "point_idx": int(row["point_idx"]),
                    "x": float(row["x"]),
                    "y": float(row["y"]),
                    "heading": float(row["heading"]),
                    "s": float(row["s"]),
                    "l": float(row["l"]),
                    "is_target": int(row["is_target"]),
                }
            )
    for rows in frames.values():
        rows.sort(key=lambda item: item["point_idx"])
    return frames


def read_obstacles(path: Path):
    frames = {}
    if path is None or not path.is_file():
        return frames
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                frame_id = int(row["frame_id"])
                frames.setdefault(frame_id, []).append(
                    {
                        "frame_id": frame_id,
                        "sim_time": float(row["sim_time"]),
                        "actor_id": int(row["actor_id"]),
                        "actor_name": row.get("actor_name", ""),
                        "actor_type": int(row.get("actor_type", "0")),
                        "x": float(row["x"]),
                        "y": float(row["y"]),
                        "h": float(row.get("h", "0")),
                        "length": float(row.get("length", "0")),
                        "width": float(row.get("width", "0")),
                        "distance_to_ego": float(row.get("distance_to_ego", "nan")),
                    }
                )
            except (KeyError, ValueError):
                continue
    return frames


def sample_ids(frame_ids, max_frames: int):
    if max_frames <= 0 or len(frame_ids) <= max_frames:
        return frame_ids
    if max_frames == 1:
        return [frame_ids[0]]

    sampled = []
    seen = set()
    last = len(frame_ids) - 1
    for i in range(max_frames):
        index = round(last * i / (max_frames - 1))
        if index not in seen:
            sampled.append(frame_ids[index])
            seen.add(index)
    return sampled


def all_xy(points):
    return [p[0] for p in points], [p[1] for p in points]


def obstacle_label(obstacle):
    return obstacle["actor_name"] if obstacle["actor_name"] else f"actor_{obstacle['actor_id']}"


def obstacle_box_points(obstacle):
    length = max(obstacle["length"], 0.5)
    width = max(obstacle["width"], 0.5)
    half_l = 0.5 * length
    half_w = 0.5 * width
    heading = obstacle["h"]
    cos_h = math.cos(heading)
    sin_h = math.sin(heading)
    local = [
        (half_l, half_w),
        (half_l, -half_w),
        (-half_l, -half_w),
        (-half_l, half_w),
    ]
    return [
        (obstacle["x"] + lx * cos_h - ly * sin_h,
         obstacle["y"] + lx * sin_h + ly * cos_h)
        for lx, ly in local
    ]


def obstacle_xy(obstacles):
    xs = []
    ys = []
    for obstacle in obstacles:
        xs.append(obstacle["x"])
        ys.append(obstacle["y"])
        for x, y in obstacle_box_points(obstacle):
            xs.append(x)
            ys.append(y)
    return xs, ys


def expand_limits(xs, ys, aspect: float, padding: float):
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    width = max(max_x - min_x + 2.0 * padding, 20.0)
    height = max(max_y - min_y + 2.0 * padding, 12.0)

    if width / height > aspect:
        height = width / aspect
    else:
        width = height * aspect

    center_x = 0.5 * (min_x + max_x)
    center_y = 0.5 * (min_y + max_y)
    return (
        center_x - 0.5 * width,
        center_x + 0.5 * width,
        center_y - 0.5 * height,
        center_y + 0.5 * height,
    )


def draw_obstacles(ax, obstacles):
    for index, obstacle in enumerate(obstacles):
        box = obstacle_box_points(obstacle)
        closed = box + [box[0]]
        xs, ys = all_xy(closed)
        label = "obstacle" if index == 0 else None
        ax.fill(xs, ys, facecolor="#e8710a", edgecolor="#e8710a",
                linewidth=1.3, alpha=0.18, label=label, zorder=5)
        ax.scatter([obstacle["x"]], [obstacle["y"]], s=32,
                   color="#e8710a", edgecolors="white", linewidths=0.8,
                   zorder=6)
        ax.text(obstacle["x"], obstacle["y"] + 0.7, obstacle_label(obstacle),
                fontsize=7, color="#8a4b08", ha="center", va="bottom",
                zorder=7)


def find_target(plan_rows):
    for row in plan_rows:
        if row["is_target"] == 1:
            return row
    target_idx = plan_rows[0]["target_idx"]
    for row in plan_rows:
        if row["point_idx"] == target_idx:
            return row
    return plan_rows[-1]


def frame_points(reference_rows, plan_rows, trail_points, obstacles):
    xs = [row["x"] for row in plan_rows]
    ys = [row["y"] for row in plan_rows]
    first = plan_rows[0]
    xs.extend([first["ego_x"]])
    ys.extend([first["ego_y"]])
    if reference_rows:
        xs.extend(row["ref_x"] for row in reference_rows)
        ys.extend(row["ref_y"] for row in reference_rows)
        first_ref = reference_rows[0]
        xs.extend([first_ref["projection_x"], first_ref["target_x"]])
        ys.extend([first_ref["projection_y"], first_ref["target_y"]])
    for x, y in trail_points:
        xs.append(x)
        ys.append(y)
    obstacle_xs, obstacle_ys = obstacle_xy(obstacles)
    xs.extend(obstacle_xs)
    ys.extend(obstacle_ys)
    return xs, ys


def make_gif(global_csv: Path,
             reference_csv: Path,
             obstacle_csv: Path,
             trajectory_csv: Path,
             output_gif: Path,
             max_frames: int,
             fps: int,
             dpi: int,
             trail: int,
             full_route: bool,
             show_obstacles: bool,
             scenario: str):
    print(f"[gif] scenario: {scenario}", flush=True)
    print(f"[gif] global_csv: {global_csv}", flush=True)
    print(f"[gif] reference_csv: {reference_csv}", flush=True)
    print(f"[gif] obstacle_csv: {obstacle_csv}", flush=True)
    print(f"[gif] trajectory_csv: {trajectory_csv}", flush=True)
    print(f"[gif] output: {output_gif}", flush=True)

    run_hint = (
        "Run the demo first: "
        f"python3 examples/DEMO1_rsim_driver_emplanner/run_demo.py --scenario {scenario}"
    )
    if not global_csv.is_file():
        raise SystemExit(f"ERROR: global path CSV not found: {global_csv}\n{run_hint}")
    if not reference_csv.is_file():
        raise SystemExit(f"ERROR: reference-line CSV not found: {reference_csv}\n{run_hint}")
    if show_obstacles and not obstacle_csv.is_file():
        raise SystemExit(f"ERROR: obstacle CSV not found: {obstacle_csv}\n{run_hint}")
    if not trajectory_csv.is_file():
        raise SystemExit(f"ERROR: ego trajectory CSV not found: {trajectory_csv}\n{run_hint}")

    try:
        import matplotlib

        matplotlib.use("Agg")

        import matplotlib.pyplot as plt
        from matplotlib.animation import FuncAnimation, PillowWriter
    except ImportError as exc:
        raise SystemExit(
            "ERROR: matplotlib and pillow are required to generate the GIF. "
            "Run this script in the demo Python environment."
        ) from exc

    global_points = read_global_path(global_csv)
    reference_by_frame = read_reference_motion(reference_csv)
    trajectory_by_frame = read_ego_trajectory(trajectory_csv)
    obstacles_by_frame = read_obstacles(obstacle_csv) if show_obstacles else {}

    if len(global_points) < 2:
        raise SystemExit(f"ERROR: not enough global path points: {global_csv}")
    if not trajectory_by_frame:
        raise SystemExit(f"ERROR: no trajectory frames: {trajectory_csv}")

    frame_ids = sample_ids(sorted(trajectory_by_frame), max_frames)
    output_gif.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(10.8, 6.4))
    aspect = 10.8 / 6.4
    route_xs, route_ys = all_xy(global_points)

    route_limit_xs = list(route_xs)
    route_limit_ys = list(route_ys)
    for rows in trajectory_by_frame.values():
        route_limit_xs.extend(row["x"] for row in rows)
        route_limit_ys.extend(row["y"] for row in rows)
        route_limit_xs.append(rows[0]["ego_x"])
        route_limit_ys.append(rows[0]["ego_y"])
    if obstacles_by_frame:
        all_obstacles = [obs for rows in obstacles_by_frame.values() for obs in rows]
        obstacle_xs, obstacle_ys = obstacle_xy(all_obstacles)
        route_limit_xs.extend(obstacle_xs)
        route_limit_ys.extend(obstacle_ys)
    route_limits = expand_limits(route_limit_xs, route_limit_ys, aspect, padding=8.0)

    sampled_ego = [
        (trajectory_by_frame[frame_id][0]["ego_x"],
         trajectory_by_frame[frame_id][0]["ego_y"])
        for frame_id in frame_ids
    ]

    def draw(frame_index: int):
        frame_id = frame_ids[frame_index]
        plan_rows = trajectory_by_frame[frame_id]
        reference_rows = reference_by_frame.get(frame_id, [])
        current_obstacles = obstacles_by_frame.get(frame_id, [])
        first = plan_rows[0]
        target = find_target(plan_rows)
        trail_begin = max(0, frame_index - max(0, trail))
        trail_points = sampled_ego[trail_begin:frame_index + 1]

        ax.clear()
        ax.plot(route_xs, route_ys, color="#9aa0a6", linewidth=1.4,
                label="global path", zorder=1)

        if reference_rows:
            ref_xs = [row["ref_x"] for row in reference_rows]
            ref_ys = [row["ref_y"] for row in reference_rows]
            ax.plot(ref_xs, ref_ys, color="#188038", linewidth=2.4,
                    label="reference line", zorder=3)
            ax.scatter([reference_rows[0]["projection_x"]],
                       [reference_rows[0]["projection_y"]],
                       s=42, facecolors="white", edgecolors="#202124",
                       linewidths=1.2, label="projection", zorder=7)

        plan_xs = [row["x"] for row in plan_rows]
        plan_ys = [row["y"] for row in plan_rows]
        ax.plot(plan_xs, plan_ys, color="#1a73e8", linewidth=2.2,
                marker=".", markersize=3.2, label="DP Cartesian plan", zorder=4)

        if len(trail_points) >= 2:
            trail_xs, trail_ys = all_xy(trail_points)
            ax.plot(trail_xs, trail_ys, color="#f29900", linewidth=2.5,
                    alpha=0.88, label="ego trajectory", zorder=5)

        if current_obstacles:
            draw_obstacles(ax, current_obstacles)

        ax.scatter([target["x"]], [target["y"]], s=72,
                   color="#d93025", edgecolors="white", linewidths=0.8,
                   label="control target", zorder=8)
        ax.scatter([first["ego_x"]], [first["ego_y"]], s=82,
                   color="#202124", edgecolors="white", linewidths=0.9,
                   label="ego", zorder=9)
        ax.arrow(first["ego_x"], first["ego_y"],
                 math.cos(first["ego_h"]) * 3.0,
                 math.sin(first["ego_h"]) * 3.0,
                 width=0.16, head_width=0.9, head_length=1.2,
                 length_includes_head=True, color="#202124", zorder=10)

        if full_route:
            limits = route_limits
        else:
            xs, ys = frame_points(reference_rows, plan_rows, trail_points,
                                  current_obstacles)
            limits = expand_limits(xs, ys, aspect, padding=8.0)

        ax.set_xlim(limits[0], limits[1])
        ax.set_ylim(limits[2], limits[3])
        ax.set_aspect("equal", adjustable="box")
        ax.grid(True, color="#e6e8eb", linewidth=0.8)
        ax.set_xlabel("world x (m)")
        ax.set_ylabel("world y (m)")
        ax.set_title(
            "EM planner demo "
            f"scenario={scenario} frame={frame_id} t={first['sim_time']:.2f}s "
            f"plan_points={len(plan_rows)} target_idx={first['target_idx']} "
            f"view={'global route' if full_route else 'follow'}"
        )
        ax.legend(loc="upper right", fontsize=8, framealpha=0.92)
        return []

    animation = FuncAnimation(fig,
                              draw,
                              frames=len(frame_ids),
                              interval=1000.0 / max(1, fps),
                              blit=False)
    writer = PillowWriter(fps=max(1, fps))
    animation.save(output_gif, writer=writer, dpi=dpi)
    plt.close(fig)

    print(f"[gif] global points: {len(global_points)}")
    print(f"[gif] trajectory frames: {len(trajectory_by_frame)} sampled: {len(frame_ids)}")
    print(f"[gif] reference frames: {len(reference_by_frame)}")
    if show_obstacles and obstacle_csv.is_file():
        obstacle_rows = sum(len(rows) for rows in obstacles_by_frame.values())
        print(f"[gif] obstacle rows: {obstacle_rows} frames: {len(obstacles_by_frame)}")
    print(f"[gif] output: {output_gif}")


def parse_args():
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description="Create the combined demo GIF from plugin CSV outputs."
    )
    parser.add_argument("--scenario",
                        choices=["resource", "staticobstacles"],
                        default="staticobstacles",
                        help="Output scenario directory to use for default CSV paths.")
    parser.add_argument("--global-csv",
                        type=Path,
                        default=None)
    parser.add_argument("--reference-csv",
                        type=Path,
                        default=None)
    parser.add_argument("--obstacle-csv",
                        type=Path,
                        default=None)
    parser.add_argument("--trajectory-csv",
                        type=Path,
                        default=None)
    parser.add_argument("--output",
                        type=Path,
                        default=None)
    parser.add_argument("--max-frames",
                        type=int,
                        default=160,
                        help="Uniformly sample at most this many frames; <=0 uses all frames.")
    parser.add_argument("--fps", type=int, default=12)
    parser.add_argument("--dpi", type=int, default=110)
    parser.add_argument("--trail",
                        type=int,
                        default=24,
                        help="Number of sampled ego positions to keep as a trail.")
    view_group = parser.add_mutually_exclusive_group()
    view_group.add_argument("--follow-reference",
                            action="store_true",
                            help="Follow the current frame instead of using the full-route view.")
    view_group.add_argument("--full-route",
                            action="store_true",
                            help="Use the fixed full-route view. This is the default.")
    parser.add_argument("--no-obstacles",
                        action="store_true",
                        help="Do not overlay obstacles even if obstacles.csv exists.")
    return parser.parse_args()


def default_csv_dir(scenario: str):
    here = Path(__file__).resolve().parent
    return here / "output" / scenario / "csv"


if __name__ == "__main__":
    args = parse_args()
    csv_dir = default_csv_dir(args.scenario)
    make_gif(args.global_csv or csv_dir / "global_path_world_points.csv",
             args.reference_csv or csv_dir / "reference_line_motion.csv",
             args.obstacle_csv or csv_dir / "obstacles.csv",
             args.trajectory_csv or csv_dir / "ego_trajectory.csv",
             args.output or csv_dir / "demo_visualization.gif",
             args.max_frames,
             args.fps,
             args.dpi,
             args.trail,
             not args.follow_reference,
             not args.no_obstacles,
             args.scenario)
