#!/usr/bin/env python3
"""
Create one GIF for the EM-planner demo.

Inputs default to output/<scenario>/csv files generated by run_demo.py:
  - global_path_world_points.csv
  - reference_line_motion.csv
  - obstacles.csv
  - ego_trajectory.csv
  - dp_trajectory.csv (optional)

The ego_trajectory.csv file is written by the C++ plugin and contains the
per-frame QP path after Frenet-to-Cartesian conversion.
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

DEFAULT_LEFT_ROAD_BOUNDARY_L = 3.5
DEFAULT_RIGHT_ROAD_BOUNDARY_L = -3.5
DEFAULT_OBSTACLE_LATERAL_BUFFER = 1.5
NEAR_DISTANCE_DISPLAY_M = 12.0
CAUTION_DISTANCE_M = 5.0
CRITICAL_DISTANCE_M = 2.5
TARGET_SPEED_MPS = 13.0
EGO_INFO_CARD_OFFSET_POINTS = (18, -34)


def parse_float(row, *names, default="nan"):
    for name in names:
        value = row.get(name)
        if value not in (None, ""):
            return float(value)
    return float(default)


def read_global_path(path: Path):
    points = []
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            points.append((float(row["x"]), float(row["y"])))
    return points


def read_reference_motion(path: Path):
    frames = {}
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            frame_id = int(row["frame_id"])
            frames.setdefault(frame_id, []).append(
                {
                    "frame_id": frame_id,
                    "sim_time": float(row["sim_time"]),
                    "ego_x": float(row["ego_x"]),
                    "ego_y": float(row["ego_y"]),
                    "global_match_idx": int(row["global_match_idx"]),
                    "projection_x": float(row["projection_x"]),
                    "projection_y": float(row["projection_y"]),
                    "projection_hdg": float(row["projection_hdg"]),
                    "target_idx": int(row["target_idx"]),
                    "point_idx": int(row["point_idx"]),
                    "ref_s": float(row["ref_s"]),
                    "ref_x": float(row["ref_x"]),
                    "ref_y": float(row["ref_y"]),
                    "ref_hdg": float(row["ref_hdg"]),
                    "target_x": float(row["target_x"]),
                    "target_y": float(row["target_y"]),
                }
            )
    for rows in frames.values():
        rows.sort(key=lambda item: item["point_idx"])
    return frames


def read_ego_trajectory(path: Path, missing_ok: bool = False):
    frames = {}
    if missing_ok and not path.is_file():
        return frames
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            frame_id = int(row["frame_id"])
            theta = parse_float(row, "theta", "heading", default="0")
            k = parse_float(row, "k", "kappa", default="0")
            frames.setdefault(frame_id, []).append(
                {
                    "frame_id": frame_id,
                    "sim_time": float(row["sim_time"]),
                    "time_step": float(row["time_step"]),
                    "ego_x": float(row["ego_x"]),
                    "ego_y": float(row["ego_y"]),
                    "ego_h": float(row["ego_h"]),
                    "ego_speed": parse_float(row, "ego_speed"),
                    "target_idx": int(row["target_idx"]),
                    "point_idx": int(row["point_idx"]),
                    "x": float(row["x"]),
                    "y": float(row["y"]),
                    "heading": theta,
                    "theta": theta,
                    "k": k,
                    "v": parse_float(row, "v"),
                    "a": parse_float(row, "a"),
                    "time": parse_float(row, "time", default=row["sim_time"]),
                    "is_target": int(row["is_target"]),
                }
            )
    for rows in frames.values():
        rows.sort(key=lambda item: item["point_idx"])
    return frames


def read_obstacles(path: Path):
    frames = {}
    if path is None or not path.is_file():
        return frames
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                frame_id = int(row["frame_id"])
                frames.setdefault(frame_id, []).append(
                    {
                        "frame_id": frame_id,
                        "sim_time": float(row["sim_time"]),
                        "actor_id": int(row["actor_id"]),
                        "actor_name": row.get("actor_name", ""),
                        "actor_type": int(row.get("actor_type", "0")),
                        "x": float(row["x"]),
                        "y": float(row["y"]),
                        "h": float(row.get("h", "0")),
                        "length": float(row.get("length", "0")),
                        "width": float(row.get("width", "0")),
                        "s": float(row.get("s", "nan")),
                        "t": float(row.get("t", "nan")),
                        "distance_to_ego": float(row.get("distance_to_ego", "nan")),
                    }
                )
            except (KeyError, ValueError):
                continue
    return frames


def sample_ids(frame_ids, max_frames: int):
    if max_frames <= 0 or len(frame_ids) <= max_frames:
        return frame_ids
    if max_frames == 1:
        return [frame_ids[0]]

    sampled = []
    seen = set()
    last = len(frame_ids) - 1
    for i in range(max_frames):
        index = round(last * i / (max_frames - 1))
        if index not in seen:
            sampled.append(frame_ids[index])
            seen.add(index)
    return sampled


def all_xy(points):
    return [p[0] for p in points], [p[1] for p in points]


def obstacle_label(obstacle):
    return obstacle["actor_name"] if obstacle["actor_name"] else f"actor_{obstacle['actor_id']}"


def obstacle_box_points(obstacle):
    length = max(obstacle["length"], 0.5)
    width = max(obstacle["width"], 0.5)
    half_l = 0.5 * length
    half_w = 0.5 * width
    heading = obstacle["h"]
    cos_h = math.cos(heading)
    sin_h = math.sin(heading)
    local = [
        (half_l, half_w),
        (half_l, -half_w),
        (-half_l, -half_w),
        (-half_l, half_w),
    ]
    return [
        (obstacle["x"] + lx * cos_h - ly * sin_h,
         obstacle["y"] + lx * sin_h + ly * cos_h)
        for lx, ly in local
    ]


def obstacle_xy(obstacles):
    xs = []
    ys = []
    for obstacle in obstacles:
        xs.append(obstacle["x"])
        ys.append(obstacle["y"])
        for x, y in obstacle_box_points(obstacle):
            xs.append(x)
            ys.append(y)
    return xs, ys


def offset_xy(x: float, y: float, heading: float, lateral_l: float):
    normal_x = -math.sin(heading)
    normal_y = math.cos(heading)
    return x + lateral_l * normal_x, y + lateral_l * normal_y


def global_boundary_xy(global_points, lateral_l: float):
    points = []
    for i, (x, y) in enumerate(global_points):
        if len(global_points) == 1:
            heading = 0.0
        elif i == 0:
            next_x, next_y = global_points[i + 1]
            heading = math.atan2(next_y - y, next_x - x)
        elif i + 1 == len(global_points):
            prev_x, prev_y = global_points[i - 1]
            heading = math.atan2(y - prev_y, x - prev_x)
        else:
            prev_x, prev_y = global_points[i - 1]
            next_x, next_y = global_points[i + 1]
            heading = math.atan2(next_y - prev_y, next_x - prev_x)
        points.append(offset_xy(x, y, heading, lateral_l))
    return points


def boundary_xy(reference_rows, l_values):
    points = []
    for row, lateral_l in zip(reference_rows, l_values):
        points.append(offset_xy(row["ref_x"], row["ref_y"], row["ref_hdg"], lateral_l))
    return points


def project_xy_to_reference(reference_rows, x: float, y: float):
    if not reference_rows:
        return None
    if len(reference_rows) == 1:
        row = reference_rows[0]
        normal_x = -math.sin(row["ref_hdg"])
        normal_y = math.cos(row["ref_hdg"])
        lateral_l = (x - row["ref_x"]) * normal_x + (y - row["ref_y"]) * normal_y
        dist2 = (x - row["ref_x"]) ** 2 + (y - row["ref_y"]) ** 2
        return {"s": row["ref_s"], "l": lateral_l, "distance2": dist2}

    best = None
    for i in range(1, len(reference_rows)):
        prev = reference_rows[i - 1]
        curr = reference_rows[i]
        vx = curr["ref_x"] - prev["ref_x"]
        vy = curr["ref_y"] - prev["ref_y"]
        seg_len2 = vx * vx + vy * vy
        if seg_len2 <= 1e-12:
            ratio = 0.0
        else:
            ratio = ((x - prev["ref_x"]) * vx + (y - prev["ref_y"]) * vy) / seg_len2
            ratio = max(0.0, min(1.0, ratio))

        proj_x = prev["ref_x"] + vx * ratio
        proj_y = prev["ref_y"] + vy * ratio
        dist2 = (x - proj_x) ** 2 + (y - proj_y) ** 2
        heading = math.atan2(vy, vx) if seg_len2 > 1e-12 else prev["ref_hdg"]
        normal_x = -math.sin(heading)
        normal_y = math.cos(heading)
        lateral_l = (x - proj_x) * normal_x + (y - proj_y) * normal_y
        ref_s = prev["ref_s"] + (curr["ref_s"] - prev["ref_s"]) * ratio
        item = {"s": ref_s, "l": lateral_l, "distance2": dist2}
        if best is None or dist2 < best["distance2"]:
            best = item
    return best


def project_path_to_reference(reference_rows, path_rows):
    projected = []
    for row in path_rows:
        item = project_xy_to_reference(reference_rows, row["x"], row["y"])
        if item is not None:
            projected.append(item)
    projected.sort(key=lambda item: item["s"])
    return projected


def interpolate_l(projected_path, ref_s: float):
    if not projected_path:
        return 0.0
    if ref_s <= projected_path[0]["s"]:
        return projected_path[0]["l"]
    if ref_s >= projected_path[-1]["s"]:
        return projected_path[-1]["l"]
    for i in range(1, len(projected_path)):
        prev = projected_path[i - 1]
        curr = projected_path[i]
        if ref_s > curr["s"]:
            continue
        ds = curr["s"] - prev["s"]
        ratio = (ref_s - prev["s"]) / ds if abs(ds) > 1e-9 else 0.0
        return prev["l"] + (curr["l"] - prev["l"]) * max(0.0, min(1.0, ratio))
    return projected_path[-1]["l"]


def build_road_and_drivable_area(reference_rows,
                                 coarse_rows,
                                 obstacles,
                                 left_road_l: float,
                                 right_road_l: float,
                                 obstacle_lateral_buffer: float):
    if not reference_rows:
        return None

    left_l = [left_road_l for _ in reference_rows]
    right_l = [right_road_l for _ in reference_rows]
    projected_path = project_path_to_reference(reference_rows, coarse_rows)

    for obstacle in obstacles:
        obstacle_ref = project_xy_to_reference(reference_rows, obstacle["x"], obstacle["y"])
        if obstacle_ref is None:
            continue

        half_length = 0.5 * max(obstacle["length"], 0.0)
        half_extent = (
            0.5 * max(max(obstacle["length"], 0.0), max(obstacle["width"], 0.0))
            + max(obstacle_lateral_buffer, 0.0)
        )
        if (obstacle_ref["l"] < right_road_l - half_extent - 1.0 or
                obstacle_ref["l"] > left_road_l + half_extent + 1.0):
            continue

        for i, row in enumerate(reference_rows):
            if row["ref_s"] < obstacle_ref["s"] - half_length:
                continue
            if row["ref_s"] > obstacle_ref["s"] + half_length:
                continue

            coarse_l = interpolate_l(projected_path, row["ref_s"])
            if coarse_l >= obstacle_ref["l"]:
                right_l[i] = max(right_l[i], obstacle_ref["l"] + half_extent)
            else:
                left_l[i] = min(left_l[i], obstacle_ref["l"] - half_extent)

    for i in range(len(reference_rows)):
        left_l[i] = min(left_l[i], left_road_l)
        right_l[i] = max(right_l[i], right_road_l)
        if right_l[i] > left_l[i]:
            pinch_l = 0.5 * (right_l[i] + left_l[i])
            left_l[i] = pinch_l
            right_l[i] = pinch_l

    road_left = boundary_xy(reference_rows, [left_road_l] * len(reference_rows))
    road_right = boundary_xy(reference_rows, [right_road_l] * len(reference_rows))
    drivable_left = boundary_xy(reference_rows, left_l)
    drivable_right = boundary_xy(reference_rows, right_l)
    return {
        "road_left": road_left,
        "road_right": road_right,
        "drivable_left": drivable_left,
        "drivable_right": drivable_right,
    }


def flatten_xy(point_groups):
    xs = []
    ys = []
    for points in point_groups:
        for x, y in points:
            xs.append(x)
            ys.append(y)
    return xs, ys


def expand_limits(xs, ys, aspect: float, padding: float):
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    width = max(max_x - min_x + 2.0 * padding, 20.0)
    height = max(max_y - min_y + 2.0 * padding, 12.0)

    if width / height > aspect:
        height = width / aspect
    else:
        width = height * aspect

    center_x = 0.5 * (min_x + max_x)
    center_y = 0.5 * (min_y + max_y)
    return (
        center_x - 0.5 * width,
        center_x + 0.5 * width,
        center_y - 0.5 * height,
        center_y + 0.5 * height,
    )


def draw_obstacles(ax, obstacles):
    for index, obstacle in enumerate(obstacles):
        box = obstacle_box_points(obstacle)
        closed = box + [box[0]]
        xs, ys = all_xy(closed)
        label = "obstacle" if index == 0 else None
        ax.fill(xs, ys, facecolor="#e8710a", edgecolor="#e8710a",
                linewidth=1.3, alpha=0.18, label=label, zorder=5)
        ax.scatter([obstacle["x"]], [obstacle["y"]], s=32,
                   color="#e8710a", edgecolors="white", linewidths=0.8,
                   zorder=6)
        ax.text(obstacle["x"], obstacle["y"] + 0.7, obstacle_label(obstacle),
                fontsize=5.5, color="#8a4b08", ha="center", va="bottom",
                zorder=7)


def nearest_obstacle(first_plan_row, obstacles):
    if not obstacles:
        return None

    ego_x = first_plan_row["ego_x"]
    ego_y = first_plan_row["ego_y"]
    nearest = None
    for obstacle in obstacles:
        distance = math.hypot(obstacle["x"] - ego_x, obstacle["y"] - ego_y)
        item = {
            "distance": distance,
            "label": obstacle_label(obstacle),
            "obstacle": obstacle,
        }
        if nearest is None or distance < nearest["distance"]:
            nearest = item
    return nearest


def format_metric(value, unit):
    if not math.isfinite(value):
        return "--"
    return f"{value:.2f} {unit}"


def ego_motion_style(acceleration, target_speed, current_speed):
    delta_v = target_speed - current_speed
    if math.isfinite(acceleration) and acceleration > 0.08:
        return "accelerating", "#137333", "#d7f4df"
    if math.isfinite(acceleration) and acceleration < -0.08:
        return "decelerating", "#c5221f", "#fce8e6"
    if math.isfinite(delta_v) and delta_v > 0.10:
        return "speeding up", "#137333", "#d7f4df"
    if math.isfinite(delta_v) and delta_v < -0.10:
        return "slowing down", "#c5221f", "#fce8e6"
    return "cruising", "#5f6368", "#eef2f7"


def compute_ego_speeds(trajectory_by_frame):
    frame_ids = sorted(trajectory_by_frame)
    samples = []
    speeds = {}
    for frame_id in frame_ids:
        rows = trajectory_by_frame[frame_id]
        if not rows:
            continue
        row = rows[0]
        ego_speed = row.get("ego_speed", float("nan"))
        if math.isfinite(ego_speed):
            speeds[frame_id] = max(0.0, ego_speed)
        samples.append((frame_id, row["sim_time"], row["ego_x"], row["ego_y"]))

    for index, (frame_id, sim_time, ego_x, ego_y) in enumerate(samples):
        if frame_id in speeds:
            continue
        neighbor = None
        if index > 0:
            neighbor = samples[index - 1]
        elif index + 1 < len(samples):
            neighbor = samples[index + 1]
        if neighbor is None:
            speeds[frame_id] = float("nan")
            continue
        _, neighbor_time, neighbor_x, neighbor_y = neighbor
        dt = abs(sim_time - neighbor_time)
        if dt <= 1e-9:
            speeds[frame_id] = float("nan")
            continue
        speeds[frame_id] = math.hypot(ego_x - neighbor_x,
                                      ego_y - neighbor_y) / dt
    return speeds


def draw_ego_info_card(ax, ego_row, motion_row, obstacles):
    from matplotlib.offsetbox import AnnotationBbox, TextArea, VPacker

    target_speed = TARGET_SPEED_MPS
    current_speed = motion_row.get("v", float("nan"))
    acceleration = motion_row.get("a", float("nan"))
    state, edge_color, face_color = ego_motion_style(
        acceleration, target_speed, current_speed)
    lines = [
        f"Current v {format_metric(current_speed, 'm/s')}",
        f"Accel     {format_metric(acceleration, 'm/s^2')}",
        f"Mode      {state}",
    ]

    nearest = nearest_obstacle(ego_row, obstacles)
    if nearest is not None and nearest["distance"] <= NEAR_DISTANCE_DISPLAY_M:
        lines.append(f"Nearest   {nearest['label']} {nearest['distance']:.2f} m")

    text_props = {
        "fontsize": 7.3,
        "fontfamily": "monospace",
        "color": "#202124",
    }
    text_areas = [
        TextArea(f"Target v  {format_metric(target_speed, 'm/s')}",
                 textprops={
                     **text_props,
                     "fontsize": 8.0,
                     "fontweight": "bold",
                     "color": "#0b57d0",
                 })
    ]
    text_areas.extend(TextArea(line, textprops=text_props) for line in lines)
    packed_text = VPacker(children=text_areas, align="left", pad=0, sep=1.5)

    card = AnnotationBbox(
        packed_text,
        (ego_row["ego_x"], ego_row["ego_y"]),
        xybox=EGO_INFO_CARD_OFFSET_POINTS,
        xycoords="data",
        boxcoords="offset points",
        box_alignment=(0.0, 1.0),
        frameon=True,
        bboxprops={
            "boxstyle": "round,pad=0.36,rounding_size=0.08",
            "facecolor": face_color,
            "edgecolor": edge_color,
            "linewidth": 0.9,
            "alpha": 0.86,
        },
        arrowprops={
            "arrowstyle": "-",
            "color": edge_color,
            "linewidth": 0.9,
            "shrinkA": 0.0,
            "shrinkB": 4.0,
        },
    )
    card.set_zorder(30)
    ax.add_artist(card)


def find_target(plan_rows):
    for row in plan_rows:
        if row["is_target"] == 1:
            return row
    target_idx = plan_rows[0]["target_idx"]
    for row in plan_rows:
        if row["point_idx"] == target_idx:
            return row
    return plan_rows[-1]


def frame_points(reference_rows, plan_rows, trail_points, obstacles, extra_point_groups=None):
    xs = [row["x"] for row in plan_rows]
    ys = [row["y"] for row in plan_rows]
    first = plan_rows[0]
    xs.extend([first["ego_x"]])
    ys.extend([first["ego_y"]])
    if reference_rows:
        xs.extend(row["ref_x"] for row in reference_rows)
        ys.extend(row["ref_y"] for row in reference_rows)
        first_ref = reference_rows[0]
        xs.extend([first_ref["projection_x"], first_ref["target_x"]])
        ys.extend([first_ref["projection_y"], first_ref["target_y"]])
    for x, y in trail_points:
        xs.append(x)
        ys.append(y)
    obstacle_xs, obstacle_ys = obstacle_xy(obstacles)
    xs.extend(obstacle_xs)
    ys.extend(obstacle_ys)
    if extra_point_groups:
        extra_xs, extra_ys = flatten_xy(extra_point_groups)
        xs.extend(extra_xs)
        ys.extend(extra_ys)
    return xs, ys


def make_gif(global_csv: Path,
             reference_csv: Path,
             obstacle_csv: Path,
             trajectory_csv: Path,
             dp_trajectory_csv: Path,
             output_gif: Path,
             max_frames: int,
             fps: int,
             dpi: int,
             trail: int,
             full_route: bool,
             show_obstacles: bool,
             scenario: str,
             left_road_l: float,
             right_road_l: float,
             obstacle_lateral_buffer: float):
    print(f"[gif] scenario: {scenario}", flush=True)
    print(f"[gif] global_csv: {global_csv}", flush=True)
    print(f"[gif] reference_csv: {reference_csv}", flush=True)
    print(f"[gif] obstacle_csv: {obstacle_csv}", flush=True)
    print(f"[gif] qp_trajectory_csv: {trajectory_csv}", flush=True)
    print(f"[gif] dp_trajectory_csv: {dp_trajectory_csv}", flush=True)
    print(f"[gif] output: {output_gif}", flush=True)

    run_hint = (
        "Run the demo first: "
        f"python3 examples/DEMO1_rsim_driver_emplanner/run_demo.py --scenario {scenario}"
    )
    if not global_csv.is_file():
        raise SystemExit(f"ERROR: global path CSV not found: {global_csv}\n{run_hint}")
    if not reference_csv.is_file():
        raise SystemExit(f"ERROR: reference-line CSV not found: {reference_csv}\n{run_hint}")
    if show_obstacles and not obstacle_csv.is_file():
        raise SystemExit(f"ERROR: obstacle CSV not found: {obstacle_csv}\n{run_hint}")
    if not trajectory_csv.is_file():
        raise SystemExit(f"ERROR: ego trajectory CSV not found: {trajectory_csv}\n{run_hint}")

    try:
        import matplotlib

        matplotlib.use("Agg")

        import matplotlib.pyplot as plt
        from matplotlib.animation import FuncAnimation, PillowWriter
    except ImportError as exc:
        raise SystemExit(
            "ERROR: matplotlib and pillow are required to generate the GIF. "
            "Run this script in the demo Python environment."
        ) from exc

    global_points = read_global_path(global_csv)
    reference_by_frame = read_reference_motion(reference_csv)
    trajectory_by_frame = read_ego_trajectory(trajectory_csv)
    dp_by_frame = read_ego_trajectory(dp_trajectory_csv, missing_ok=True)
    obstacles_by_frame = read_obstacles(obstacle_csv) if show_obstacles else {}

    if len(global_points) < 2:
        raise SystemExit(f"ERROR: not enough global path points: {global_csv}")
    if not trajectory_by_frame:
        raise SystemExit(f"ERROR: no trajectory frames: {trajectory_csv}")

    frame_ids = sample_ids(sorted(trajectory_by_frame), max_frames)
    output_gif.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(10.8, 6.4))
    fig.subplots_adjust(left=0.075, right=0.985, top=0.91, bottom=0.11)
    plot_box = ax.get_position()
    aspect = (10.8 * plot_box.width) / (6.4 * plot_box.height)
    route_xs, route_ys = all_xy(global_points)
    global_left_boundary = global_boundary_xy(global_points, left_road_l)
    global_right_boundary = global_boundary_xy(global_points, right_road_l)
    global_road_polygon = global_left_boundary + list(reversed(global_right_boundary))

    route_limit_xs = list(route_xs)
    route_limit_ys = list(route_ys)
    boundary_xs, boundary_ys = flatten_xy([global_left_boundary, global_right_boundary])
    route_limit_xs.extend(boundary_xs)
    route_limit_ys.extend(boundary_ys)
    for rows in trajectory_by_frame.values():
        route_limit_xs.extend(row["x"] for row in rows)
        route_limit_ys.extend(row["y"] for row in rows)
        route_limit_xs.append(rows[0]["ego_x"])
        route_limit_ys.append(rows[0]["ego_y"])
    if obstacles_by_frame:
        all_obstacles = [obs for rows in obstacles_by_frame.values() for obs in rows]
        obstacle_xs, obstacle_ys = obstacle_xy(all_obstacles)
        route_limit_xs.extend(obstacle_xs)
        route_limit_ys.extend(obstacle_ys)
    route_limits = expand_limits(route_limit_xs, route_limit_ys, aspect, padding=8.0)

    sampled_ego = [
        (trajectory_by_frame[frame_id][0]["ego_x"],
         trajectory_by_frame[frame_id][0]["ego_y"])
        for frame_id in frame_ids
    ]

    def draw(frame_index: int):
        frame_id = frame_ids[frame_index]
        plan_rows = trajectory_by_frame[frame_id]
        dp_rows = dp_by_frame.get(frame_id, [])
        reference_rows = reference_by_frame.get(frame_id, [])
        current_obstacles = obstacles_by_frame.get(frame_id, [])
        coarse_rows = dp_rows if dp_rows else plan_rows
        first = plan_rows[0]
        target = find_target(plan_rows)
        trail_begin = max(0, frame_index - max(0, trail))
        trail_points = sampled_ego[trail_begin:frame_index + 1]

        ax.clear()
        road_poly_xs, road_poly_ys = all_xy(global_road_polygon)
        ax.fill(road_poly_xs, road_poly_ys, facecolor="#d93025", edgecolor="none",
                alpha=0.20, label="non-drivable area", zorder=0)
        left_xs, left_ys = all_xy(global_left_boundary)
        right_xs, right_ys = all_xy(global_right_boundary)
        ax.plot(left_xs, left_ys, color="#5f6368", linewidth=1.2,
                linestyle="-.", alpha=0.9, label="road boundary", zorder=2)
        ax.plot(right_xs, right_ys, color="#5f6368", linewidth=1.2,
                linestyle="-.", alpha=0.9, zorder=2)
        ax.plot(route_xs, route_ys, color="#9aa0a6", linewidth=1.4,
                label="global route", zorder=1)

        if reference_rows:
            area = build_road_and_drivable_area(reference_rows,
                                               coarse_rows,
                                               current_obstacles,
                                               left_road_l,
                                               right_road_l,
                                               obstacle_lateral_buffer)
            if area is not None:
                drivable_polygon = (
                    area["drivable_left"] +
                    list(reversed(area["drivable_right"]))
                )
                poly_xs, poly_ys = all_xy(drivable_polygon)
                ax.fill(poly_xs, poly_ys, facecolor="#34a853", edgecolor="none",
                        alpha=0.42, label="drivable area", zorder=3)
                drv_left_xs, drv_left_ys = all_xy(area["drivable_left"])
                drv_right_xs, drv_right_ys = all_xy(area["drivable_right"])
                ax.plot(drv_left_xs, drv_left_ys, color="#188038", linewidth=0.85,
                        alpha=0.72, label="drivable boundary", zorder=4)
                ax.plot(drv_right_xs, drv_right_ys, color="#188038", linewidth=0.85,
                        alpha=0.72, zorder=4)

            ref_xs = [row["ref_x"] for row in reference_rows]
            ref_ys = [row["ref_y"] for row in reference_rows]
            ax.plot(ref_xs, ref_ys, color="#188038", linewidth=1.2,
                    label="reference line", zorder=3)
            ax.scatter([reference_rows[0]["projection_x"]],
                       [reference_rows[0]["projection_y"]],
                       s=42, facecolors="white", edgecolors="#202124",
                       linewidths=1.2, label="projection", zorder=7)

        if dp_rows:
            dp_xs = [row["x"] for row in dp_rows]
            dp_ys = [row["y"] for row in dp_rows]
            ax.plot(dp_xs, dp_ys, color="#7e57c2", linewidth=0.85,
                    linestyle=(0, (4, 3)), alpha=0.96,
                    label="DP coarse path", zorder=4)

        plan_xs = [row["x"] for row in plan_rows]
        plan_ys = [row["y"] for row in plan_rows]
        ax.plot(plan_xs, plan_ys, color="#1a73e8", linewidth=1.4,
                linestyle="-", marker=".", markersize=2.0,
                label="QP smoothed path", zorder=5)

        if len(trail_points) >= 2:
            trail_xs, trail_ys = all_xy(trail_points)
            ax.plot(trail_xs, trail_ys, color="#f29900", linewidth=1.6,
                    alpha=0.88, label="executed ego trail", zorder=6)

        if current_obstacles:
            draw_obstacles(ax, current_obstacles)

        ax.scatter([target["x"]], [target["y"]], s=72,
                   color="#d93025", edgecolors="white", linewidths=0.8,
                   label="next control target", zorder=8)
        ax.scatter([first["ego_x"]], [first["ego_y"]], s=82,
                   color="#202124", edgecolors="white", linewidths=0.9,
                   label="ego", zorder=9)
        ax.arrow(first["ego_x"], first["ego_y"],
                 math.cos(first["ego_h"]) * 3.0,
                 math.sin(first["ego_h"]) * 3.0,
                 width=0.16, head_width=0.9, head_length=1.2,
                 length_includes_head=True, color="#202124", zorder=10)

        if full_route:
            limits = route_limits
        else:
            extra_groups = []
            if reference_rows:
                area_for_limits = build_road_and_drivable_area(reference_rows,
                                                               coarse_rows,
                                                               current_obstacles,
                                                               left_road_l,
                                                               right_road_l,
                                                               obstacle_lateral_buffer)
                if area_for_limits is not None:
                    extra_groups = [
                        area_for_limits["drivable_left"],
                        area_for_limits["drivable_right"],
                    ]
            xs, ys = frame_points(reference_rows, plan_rows, trail_points,
                                  current_obstacles, extra_groups)
            limits = expand_limits(xs, ys, aspect, padding=8.0)

        ax.set_xlim(limits[0], limits[1])
        ax.set_ylim(limits[2], limits[3])
        ax.set_aspect("equal", adjustable="box")
        ax.grid(True, color="#e6e8eb", linewidth=0.8)
        ax.set_xlabel("world x (m)")
        ax.set_ylabel("world y (m)")
        ax.set_title(
            "EM planner demo "
            f"scenario={scenario} frame={frame_id} t={first['sim_time']:.2f}s "
            f"qp_points={len(plan_rows)} dp_points={len(dp_rows)} "
            f"target_idx={first['target_idx']} "
            f"view={'global route' if full_route else 'follow'}"
        )
        ax.legend(loc="upper right", fontsize=8, framealpha=0.92)
        draw_ego_info_card(ax, first, target, current_obstacles)
        return []

    animation = FuncAnimation(fig,
                              draw,
                              frames=len(frame_ids),
                              interval=1000.0 / max(1, fps),
                              blit=False)
    writer = PillowWriter(fps=max(1, fps))
    animation.save(output_gif, writer=writer, dpi=dpi)
    plt.close(fig)

    print(f"[gif] global points: {len(global_points)}")
    print(f"[gif] trajectory frames: {len(trajectory_by_frame)} sampled: {len(frame_ids)}")
    print(f"[gif] dp trajectory frames: {len(dp_by_frame)}")
    print(f"[gif] reference frames: {len(reference_by_frame)}")
    if show_obstacles and obstacle_csv.is_file():
        obstacle_rows = sum(len(rows) for rows in obstacles_by_frame.values())
        print(f"[gif] obstacle rows: {obstacle_rows} frames: {len(obstacles_by_frame)}")
    print(f"[gif] output: {output_gif}")


def parse_args():
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description="Create the combined demo GIF from plugin CSV outputs."
    )
    parser.add_argument("--scenario",
                        choices=["resource", "staticobstacles"],
                        default="staticobstacles",
                        help="Output scenario directory to use for default CSV paths.")
    parser.add_argument("--global-csv",
                        type=Path,
                        default=None)
    parser.add_argument("--reference-csv",
                        type=Path,
                        default=None)
    parser.add_argument("--obstacle-csv",
                        type=Path,
                        default=None)
    parser.add_argument("--trajectory-csv",
                        type=Path,
                        default=None)
    parser.add_argument("--dp-trajectory-csv",
                        type=Path,
                        default=None,
                        help="Optional Cartesian DP coarse path CSV. If absent, the DP line is hidden.")
    parser.add_argument("--output",
                        type=Path,
                        default=None)
    parser.add_argument("--max-frames",
                        type=int,
                        default=0,
                        help="Uniformly sample at most this many frames; <=0 uses all frames.")
    parser.add_argument("--fps", type=int, default=12)
    parser.add_argument("--dpi", type=int, default=110)
    parser.add_argument("--trail",
                        type=int,
                        default=24,
                        help="Number of sampled ego positions to keep as a trail.")
    view_group = parser.add_mutually_exclusive_group()
    view_group.add_argument("--follow-reference",
                            action="store_true",
                            help="Follow the current frame instead of using the full-route view.")
    view_group.add_argument("--full-route",
                            action="store_true",
                            help="Use the fixed full-route view. This is the default.")
    parser.add_argument("--no-obstacles",
                        action="store_true",
                        help="Do not overlay obstacles even if obstacles.csv exists.")
    parser.add_argument("--left-road-boundary-l",
                        type=float,
                        default=DEFAULT_LEFT_ROAD_BOUNDARY_L,
                        help="Left road boundary lateral offset in Frenet l.")
    parser.add_argument("--right-road-boundary-l",
                        type=float,
                        default=DEFAULT_RIGHT_ROAD_BOUNDARY_L,
                        help="Right road boundary lateral offset in Frenet l.")
    parser.add_argument("--obstacle-lateral-buffer",
                        type=float,
                        default=DEFAULT_OBSTACLE_LATERAL_BUFFER,
                        help="Lateral buffer used to shrink the visual drivable area.")
    return parser.parse_args()


def default_csv_dir(scenario: str):
    here = Path(__file__).resolve().parent
    return here / "output" / scenario / "csv"


if __name__ == "__main__":
    args = parse_args()
    csv_dir = default_csv_dir(args.scenario)
    make_gif(args.global_csv or csv_dir / "global_path_world_points.csv",
             args.reference_csv or csv_dir / "reference_line_motion.csv",
             args.obstacle_csv or csv_dir / "obstacles.csv",
             args.trajectory_csv or csv_dir / "ego_trajectory.csv",
             args.dp_trajectory_csv or csv_dir / "dp_trajectory.csv",
             args.output or csv_dir / "demo_visualization.gif",
             args.max_frames,
             args.fps,
             args.dpi,
             args.trail,
             not args.follow_reference,
             not args.no_obstacles,
             args.scenario,
             args.left_road_boundary_l,
             args.right_road_boundary_l,
             args.obstacle_lateral_buffer)
